### ISSUE TITLE
Variables in the list

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#29]
In the moment they're over 300 variables in the list, which makes hard to fin the right one.
I think the wheel data itself shouldn't global, only the processed data should global.

**Comment by n9yty** [comment]
I don’t know who may be using it in what way, perhaps both ways are useful. The variables can be searched or filtered so that helps. I had thought about taking the wheel (not by category out, but I have no way to know if anyone has used them. Perhaps not as it is new. Everyone has different ideas of what they find useful.

**Comment by sstaub** [comment]
I think the way you do it in the example is the right way for wheels, to mimic the console behavior is that what users want.
For the parameters itself it is OK. But 400 variables for wheel access is nothing what users want to handle.

**Comment by n9yty** [comment]
I understand. I am reworking it to manage the wheel data internally in the module so all the raw data is not exposed in variables, just the ones per-category as used in the example config. I am leaving the old code commented out at this point in case it causes problems if someone had already started using it.
