### ISSUE TITLE
Course, Fine, Acceleration improvements

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#33]
Course, Fine, Acceleration, see #16
- Fine doesn't work as expected you must send /eos/wheel/fine/<Parameter> for the correct behavior of the parameter. 
- Course gives the MSB and fine the LSB off of a 16bit Parameter.
- Also you should "Course" rename in "Acc" (Acceleration) because "course" is the regular mode by design.

**Comment by n9yty** [comment]
I have done that, perhaps the sample file changes were not pushed. That is all for the user to configure anyway it is not the core module.On Jun 21, 2023, at 3:21 PM, Stefan Staub ***@***.***> wrote:﻿
Course, Fine, Acceleration, see #16

Fine doesn't work as expected you must send /eos/wheel/fine/ for the correct behavior of the parameter.
Course gives the MSB and fine the LSB off of a 16bit Parameter.
Also you should "Course" rename in "Acc" (Acceleration) because "course" is the regular mode by design.

**Comment by sstaub** [comment]
Work as expected now, thank you for the great work.
