### ISSUE TITLE
Help in GUI

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion-module-etc-eos#41]
Companion v3.2.0+6242-beta-84573690, the help in the GUI shows version 2.0.6 instead 2.0.7

**Comment by n9yty** [comment]
Hi @sstaub, I'm a bit confused on this one. The current version that I last pushed is 2.0.8. When I open the Companion GUI at the very top it shows v0.0.0, because it can not pull from the project version so it was never set (even from before I became involved).

Where exactly are you seeing version 2.0.6 still being listed? I'd like to fix it if I can find it.

**Comment by sstaub** [comment]
Here is a screenshot with the latest beta of companion 
<img width="1579" alt="Bildschirmfoto 2023-10-23 um 18 06 11" src="https://github.com/bitfocus/companion-module-etc-eos/assets/6450325/c45cff69-4cdd-48f8-b722-4e26e56cd50e">

**Comment by n9yty** [comment]
I just tagged the team in Slack to include v2.0.8 in the build process, as last night's update again only had v2.0.6 in it.

**Comment by n9yty** [comment]
@sstaub Companion Beta 3.2.0+6438 has pulled in v2.8.0 of the etc-eos module.

**Comment by sstaub** [comment]
The version is ok but the screenshots are missing.

**Comment by n9yty** [comment]
I didn’t change anything, so that is very strange. I will have a look.On Oct 25, 2023, at 2:12 AM, Stefan Staub ***@***.***> wrote:﻿
The version is ok but the screenshots are missing.

**Comment by sstaub** [comment]
This is fixed with the latest beta of companion.
