### ISSUE TITLE
Request: Add Color Crossfade to parameter list

### ISSUE THREAD

**Issue by axcrowe** [bitfocus/companion-module-etc-eos#48]
Requesting the parameter color crossfade be added to the available parameters. The console displays it as "color_crossfade"

Thank you!

**Comment by n9yty** [comment]
Can you describe where this is found/used/etc and if you see it in the debug window (tab 99) as an OSC output as a parameter being sent?

**Comment by n9yty** [comment]
I looked at this a bit more, it seems that it is an encoder wheel, and all of those are dynamically implemented so it should already be working.

I configured an "Arri Skypanel S360 C M1 CCT + RGBW 8B ECC" fixture, and it was automatically populated under the wheels/encoders COLOR group. I can confirm that the value reads out properly and is adjusted by rotating the encoder.

Were you expecting or looking for different behavior?

**Comment by axcrowe** [comment]
Hey, thanks for looking into this. 
It's a very common parameter in the Film/TV world, used by Arri Skypanels Mode 6, Astera Titan Tubes Mode 89, Outsight Vortexes, etc. It fades between "color temperature" or white light mode and RGB Color mode. 
I've confirmed that it shows up in Diagnostics

**Comment by n9yty** [comment]
Our notes crossed, see my comment above. :)

**Comment by axcrowe** [comment]
I'm modifying the basic layout to be more streamlined to use the same parameters every time. I've got intensity, tint and color temperature working just fine, but couldn't get color crossfade to work. I'm very green when it comes to coding and looking at code, but I noticed that parameter wasn't in the "param_map.js" and suspected that's why it wasn't working.
Also, while we're at it, could we add the parameters "CIE_X" and "CIE_Y"? They both show up as such in diagnostics. 
Really appreciate your time looking into this!

**Comment by n9yty** [comment]
As I mentioned, all encoder wheel stuff is not in the param map becuase it is dynamically covered.  I verified that it is operational under the wheel parameters in the current version, it looks like this generically, "eos/wheel/color_crossfade", but in the case of the fixture I'm looking at where it comes in as wheel 15 it is "eos/out/active/wheel/15, Color Crossfade" or the input as "eos/wheel/{fine|coarse}/color_crossfade".

I'm not clear yet if you can get what you need, but there is no global "color_crossfade" parameter that I can see that should go in the params file.

As for CIE_X and CIE_Y, again, since I don't use these, can you tell me what they do and where you see them in EOS so I can test?  If they are encoder wheels they should be captured already, but I don't see anything that looks like them. :)

**Comment by n9yty** [comment]
Okay, this may also cross-post with your comment if you reply, but I added a "Creamers Vortex8 M34: 8B Multi Zone XY Coordinates" fixture, and I see under the Color category of encoders (CIE_X, CIE_Y) pairs through 8 versions.  They adjust when using the encoder wheels although it requires fine mode and small values as it looks like the range is 0 to 0.8.

**Comment by axcrowe** [comment]
CIE X & Y are an alternative color space (like RGB, CMY, or Hue/Saturation). It's becoming all the rage in the film world. The color picker's default view is actually in CIE XY color space. ETC only recently added support for XY, so it works with the color picker, gel library etc.

**Comment by n9yty** [comment]
I have built a test bundle here with color_crossfade, and CIE_X/CIE_Y through 8.  

[pkg.zip](https://github.com/bitfocus/companion-module-etc-eos/files/15193476/pkg.zip)

You would have to unpack that and in Companion enable the Developer modules and point it to the directory containing that unpacked folder.  I think I see now, the old paradigm when all things were hardcoded was to use the parameters, and now with all the dynamicism they are not needed but you are trying to do it the old way. :)  The downside of this, of course, is the unending set of new parameters for fixtures that may have to be added manually when it is already covered dynamically. ;)

**Comment by axcrowe** [comment]
Awesome, I'll give this a shot! I'm excited to share our final product with you. I'm building a raspberry pi, a streamdeck plus, and a battery backup into a small pelican. The gaffer on my show is going to have to tweak specific lights that are close to set (hence the desire for the simpler mode).
I promise I won't bug you for lots of parameters! Those three should cover me for everything I want the gaffer to be able to tweak. 
The last hurdle is making groups show labels, which I addressed in a separate issue post. 
Again, I really appreciate your time and energy!

**Comment by n9yty** [comment]
You may not know, but I only got into this because I was helping the local high school when their light console went down, so being an obsessive compulsive sort I put together a nomad setup and took over this project to bring it up to Companion V3 standards. LoL  I don't actually use this currently, and then even minimally, so forgive me for not understanding all the terms. But I will do my best to keep it moving forward and serving any needs people have if it is feasible. :)

**Comment by axcrowe** [comment]
Wow, I had no idea! Very impressive that you we're able to make this without a full time involvement in the lighting world. I just assumed you were in the theatre world. Us Film/TV folk use very different terms despite using the same boards.

**Comment by n9yty** [comment]
Wrong file added previously.  I updated the link above as well has incorporating the group labels (1-20) into this version.

**Comment by n9yty** [comment]
Completed.
