### ISSUE TITLE
[BUG?]  'enc_saturation'  not work

### ISSUE THREAD

**Issue by ebiyans** [bitfocus/companion-module-etc-eos#54]
param_map.js

59 	'saturatn':				'enc_saturation',

**Comment by n9yty** [comment]
@ebiyans Can you tell me what fixture type you are working with so I can duplicate it exactly here and see what parameter is being sent?

**Comment by ebiyans** [comment]
fixture: ARRI SkyPanel S60-C  P1[12]      / ColorCrossfade 100   


-------------------------------
param_map.js  

59 'saturatn': 'enc_saturation',
---> 'saturation': 'enc_saturation',  

Maybe it will work if fix it

**Comment by n9yty** [comment]
@ebiyans Can you please answer my question? It is not a difficult one. How are you programming it (to what button/control/etc) and for what fixture?

I did find this note on a different integration, saying the name changed, but not sure how to make it backward compatible:  https://community.etcconnect.com/etclabs/f/lighthack/57010/lighthack---hue-and-saturation-2-9-vs-3-0

**Comment by ebiyans** [comment]
EosFamily v3.2.8.25   
companion 3.1.1+7001

USB-Device: Loupedeck Plus
OS: Windows11

fixture: ARRI Skypanel S60-C   P1[12ch] x20

![ETC](https://github.com/user-attachments/assets/9982cec6-850f-4389-a7ac-ff5b19326796)
![Loupedeck](https://github.com/user-attachments/assets/66bca90d-1e0b-490c-bc20-085ef5b25629)

**Comment by n9yty** [comment]
So that photo shows that you are sending an OSC hue command but you are asking about saturation?

I’m confused about how you are using enc_saturation and what return value you are expecting. What is your companion configuration for making the change (I assume similar to hue) and what is the config for the value display?

As I mentioned above, when I adjust saturation (or hue) the current version of ETC EOS no longer seems to respond with a hue or saturation value, instead it gives a combined he response. If I capture that response into global hue and saturation values it should solve the issue for you.

**Comment by n9yty** [comment]
On more note… open the diagnostics tab in ETC EOS and be sure to have it show in an out OSC commands. Then make your changes and make a note of what values are returned. I am guessing you will not see saturatn or even saturation returned as a standalone value.

**Comment by ebiyans** [comment]
![sat](https://github.com/user-attachments/assets/0f3d8633-e9ea-4a43-9a74-d2ce7399c287)

[Button text String]-[sat: $(etc-eos:enc_saturation_stringval)] 
   sat:0   <- As you said, the return value cannot be obtained.  
but, You can adjust the color by operating Hue & Sat with the Loupedeck knob.

I would like to be able to obtain "hs" and use a companion to calculate and display the values ​​of hue, saturation, CIE X, CIE Y.
I want to adjust the color of a full-color LED using Color Picker in various modes (RGB/CMY/HS).
I believe that there is no problem with the displayed value as long as it can be confirmed with ETC-EOS.


Automatic translation is used. We apologize for the inconvenience if it is difficult to read.

**Comment by n9yty** [comment]
@ebiyans I think then the "fix" is clear. I have already implemented capturing the hue and saturation from the /color/hs message that ETC EOS sends. To add to this, since it does not return values for those encoders directly, I will also set the enc_saturation and enc_hue variables.

I will push the fixes up, but it may take a little while for them to show up in the beta and even longer to ever make it into a production release.

https://github.com/bitfocus/companion-module-etc-eos/releases/tag/v2.0.12

**Comment by ebiyans** [comment]
Sorry for the poor explanation, but your quick response was amazing, and I'm very grateful.
